import { Container } from '@parkora-org/ui/src/components/atoms/Container'
import { CustomerBookings } from '@parkora-org/ui/src/components/templates/CustomerBookings'
import { IsLoggedIn } from '@parkora-org/ui/src/components/templates/IsLoggedIn'
import Head from 'next/head'

export default function Bookings() {
  return (
    <>
      <Head>
        <title>Bookings | Parkora | Krishna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-25">
        <Container className="min-h-[90vh]">
          <IsLoggedIn>
            <CustomerBookings />
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
