import { HowItWorksCustomer } from '@parkora-org/ui/src/components/templates/HowItWorksCustomer'
import Head from 'next/head'

export default function Search() {
  return (
    <>
      <Head>
        <title>How it works | Parkora | Krishna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HowItWorksCustomer />
      </main>
    </>
  )
}
