import { FormProviderSearchGarage } from '@parkora-org/forms/src/searchGarages'
import { SearchPageTemplate } from '@parkora-org/ui/src/components/templates/SearchPageTemplate'
import Head from 'next/head'

export default function Search() {
  return (
    <>
      <Head>
        <title>Search Parking | Parkora | Krishna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FormProviderSearchGarage>
          <SearchPageTemplate />
        </FormProviderSearchGarage>
      </main>
    </>
  )
}
